### PR TITLE
Added spanish and catalan translations

### PR DESCRIPTION
**Pull request by Naguissa**
- es
 - es_x_tu
 - ca

(added missing file in last PR)

### CODE REVIEW

**Comment by Naguissa** [comment]
Hello?

**Comment by andreaskou** [comment]
@Naguissa Hi, how can I help?

**Comment by Naguissa** [comment]
Hello.

I added this PR but recieved no response and it seems was not integrated.

I would know if it's denied or whatever....

**Comment by andreaskou** [comment]
There is no problem from your side, and thanks for the translations.
Unfortunately my laptop that I do my coding is for service (for a long time :( ) thus I am unable to do any work on the extension.
As soon as I have my laptop back I'll merge the pr.
But please note that there will be some minor changes on the translations on the near future.

Best regards,
Andreas

**Comment by Naguissa** [comment]
No problem!

I'm using the extension so I'll adjust them.


I thouht you deleted the email and forgot about it, that's why I added that "hello"..

**Comment by andreaskou** [comment]
Hi, there have been some changes on the translations (as promised).
So Is it ok if I deny this PR and you make a new one with the changes?

**Comment by Naguissa** [comment]
No problem, I'll update them when I have some time and create a new PR.

Cheers!

**Comment by Naguissa** [comment]
As I'm moving I forgot about this. I'll do it when I have few minutes of free time! I'm sorry!

**Comment by andreaskou** [comment]
Don't worry!
As you can see I am also not very active on the ext as well... ;)

**Pull request closed without merging**
